<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    
    <!-- Code Coverage Configuration -->
    <CollectCoverage>true</CollectCoverage>
    <CoverletOutputFormat>cobertura</CoverletOutputFormat>
    <CoverletOutput>./TestResults/</CoverletOutput>
    <ExcludeByFile>**/Migrations/**/*.cs</ExcludeByFile>
    <ExcludeByAttribute>Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute</ExcludeByAttribute>
    <Threshold>80</Threshold>
    <ThresholdType>line</ThresholdType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0"/>
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0"/>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.1"/>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.2"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0"/>
    <PackageReference Include="MSTest.TestAdapter" Version="3.1.1"/>
    <PackageReference Include="MSTest.TestFramework" Version="3.1.1"/>
    <PackageReference Include="NSubstitute" Version="5.3.0"/>
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6"/>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Looplex.Foundation\Looplex.Foundation.csproj"/>
    <ProjectReference Include="..\..\src\Looplex.SCIMv2\Looplex.SCIMv2.csproj"/>
    <ProjectReference Include="..\..\src\Looplex.OAuth2\Looplex.OAuth2.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <None Update="model.conf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="policy.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
